package dev.jordanempire.youflow.media;

import android.content.Context;
import android.content.SharedPreferences;

import androidx.annotation.NonNull;
import androidx.media3.exoplayer.source.ProgressiveMediaSource;
import androidx.preference.PreferenceManager;

import org.schabi.newpipe.extractor.stream.SubtitlesStream;

import dev.jordanempire.youflow.R;

/** Small preference backed helpers shared by the player data sources. */
public final class PlayerHelper {
    private PlayerHelper() {
    }

    @NonNull
    public static String captionLanguageOf(@NonNull final Context context,
                                           @NonNull final SubtitlesStream subtitles) {
        final String displayName = subtitles.getDisplayLanguageName();
        return displayName + (subtitles.isAutoGenerated()
                ? " (" + context.getString(R.string.caption_auto_generated) + ")" : "");
    }

    public static long getPreferredCacheSize() {
        return 64 * 1024 * 1024L;
    }

    public static long getPreferredFileSize() {
        return 2 * 1024 * 1024L; // CacheDataSink.MIN_RECOMMENDED_FRAGMENT_SIZE
    }

    public static int getProgressiveLoadIntervalBytes(@NonNull final Context context) {
        final SharedPreferences preferences = PreferenceManager.getDefaultSharedPreferences(context);
        final String preferredIntervalBytes = preferences.getString(
                context.getString(R.string.progressive_load_interval_key),
                context.getString(R.string.progressive_load_interval_default_value));

        if (context.getString(R.string.progressive_load_interval_exoplayer_default_value)
                .equals(preferredIntervalBytes)) {
            return ProgressiveMediaSource.DEFAULT_LOADING_CHECK_INTERVAL_BYTES;
        }
        // Keeping the same KiB unit used by ProgressiveMediaSource
        return Integer.parseInt(preferredIntervalBytes) * 1024;
    }
}
